import React from 'react';
import {
	AbsoluteFill,
	Easing,
	Img,
	interpolate,
	random,
	spring,
	staticFile,
	useCurrentFrame,
	useVideoConfig,
} from 'remotion';

// All coordinates are in the 1920x1080 space of the layers in public/reality/
// (generated by scripts/make_layers.py from the flat illustration).
const layer = (name: string) => staticFile(`reality/${name}.png`);

const clamp = {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'} as const;
const expoOut = Easing.bezier(0.16, 1, 0.3, 1);
const easeInOut = Easing.bezier(0.45, 0, 0.25, 1);
const slamIn = Easing.bezier(0.7, 0, 0.84, 0);

const PIVOT = {x: 1244.78, y: 518.77};
// Minute hand, base tucked under the hub ring.
const HAND: [number, number][] = [
	[1243.6, 503.8],
	[1384.88, 370.14],
	[1398.66, 398.26],
	[1255.1, 517.0],
];

// Beats (frames @ 24fps)
const REALITY_IN = 20;
const KICKS_HIT = 58;
const IN_HIT = 67;
const TICK_START = 10;
const TICK_EVERY = 24;
const TICK_DEG = 0.9;

// Smooth 1D value noise in [-1, 1].
const noise = (seed: string, t: number) => {
	const i = Math.floor(t);
	const f = t - i;
	const u = f * f * (3 - 2 * f);
	const a = random(`${seed}-${i}`) * 2 - 1;
	const b = random(`${seed}-${i + 1}`) * 2 - 1;
	return a + (b - a) * u;
};

// Damped shake impulse, 0 before the hit.
const impulse = (frame: number, at: number, seed: string, decay = 7) => {
	const t = frame - at;
	if (t < 0) return 0;
	return Math.exp(-t / decay) * noise(seed, t * 0.9);
};

const useCamera = (frame: number, duration: number) => {
	const p = interpolate(frame, [0, duration], [0, 1], {...clamp, easing: easeInOut});
	// punch-in on each hit, relaxing back
	const punch = (at: number, amt: number) =>
		frame < at ? 0 : amt * Math.exp(-(frame - at) / 9);
	const scale = 1.035 + 0.07 * p + punch(KICKS_HIT, 0.012) + punch(IN_HIT, 0.008);
	const shake = (s: string, amp: number) =>
		impulse(frame, KICKS_HIT, `${s}k`) * amp + impulse(frame, IN_HIT, `${s}i`) * amp * 0.7;
	// gate weave: sub-pixel drift like film in a projector
	const weaveX = noise('wx', frame / 5) * 0.6;
	const weaveY = noise('wy', frame / 6) * 0.6;
	const x = interpolate(p, [0, 1], [22, -26]) + shake('x', 7) + weaveX;
	const y = interpolate(p, [0, 1], [12, -8]) + shake('y', 5) + weaveY;
	const rot = shake('r', 0.18);
	return {scale, x, y, rot};
};

type Cam = ReturnType<typeof useCamera>;

// A full-frame layer that follows the camera at a given depth (1 = plate).
const Depth: React.FC<{cam: Cam; depth: number; style?: React.CSSProperties; children: React.ReactNode}> = ({
	cam,
	depth,
	style,
	children,
}) => (
	<AbsoluteFill
		style={{
			transformOrigin: '1000px 540px',
			transform: `translate(${cam.x * depth}px, ${cam.y * depth}px) rotate(${cam.rot * depth}deg) scale(${
				1 + (cam.scale - 1) * depth
			})`,
			...style,
		}}
	>
		{children}
	</AbsoluteFill>
);

const Full: React.FC<{src: string; style?: React.CSSProperties}> = ({src, style}) => (
	<Img src={src} style={{position: 'absolute', left: 0, top: 0, width: 1920, height: 1080, ...style}} />
);

const Glow: React.FC<{name: string; opacity: number}> = ({name, opacity}) => (
	<Full src={layer(name)} style={{opacity, mixBlendMode: 'screen'}} />
);

const MinuteHand: React.FC<{frame: number; fps: number}> = ({frame, fps}) => {
	let deg = 0;
	for (let t = TICK_START; t <= frame; t += TICK_EVERY) {
		deg +=
			TICK_DEG *
			spring({frame: frame - t, fps, config: {damping: 9, stiffness: 420, mass: 0.35}});
	}
	const pts = HAND.map(([x, y]) => `${x},${y}`).join(' ');
	return (
		<svg width={1920} height={1080} style={{position: 'absolute', left: 0, top: 0}}>
			<polygon
				points={pts}
				fill="#121212"
				transform={`rotate(${deg} ${PIVOT.x} ${PIVOT.y})`}
			/>
			<ellipse cx={PIVOT.x} cy={PIVOT.y} rx={22} ry={32} fill="#060506" />
		</svg>
	);
};

// "Reality": rises out of an invisible baseline mask.
const RealityLine: React.FC<{frame: number}> = ({frame}) => {
	const t = interpolate(frame, [REALITY_IN, REALITY_IN + 26], [0, 1], {...clamp, easing: expoOut});
	const y = (1 - t) * 175;
	const skew = (1 - t) * -4;
	const blur = (1 - t) * 5;
	return (
		<AbsoluteFill style={{clipPath: 'inset(290px 1250px 608px 110px)'}}>
			<Full
				src={layer('reality')}
				style={{
					transformOrigin: '380px 470px',
					transform: `translateY(${y}px) skewX(${skew}deg)`,
					filter: `blur(${blur}px)`,
				}}
			/>
		</AbsoluteFill>
	);
};

// "kicks" / "in.": drop onto the page from above the lens and hit.
const SlamWord: React.FC<{
	frame: number;
	fps: number;
	hit: number;
	box: [number, number, number, number]; // x0, y0, x1, y1
}> = ({frame, fps, hit, box}) => {
	const [x0, y0, x1, y1] = box;
	const fall = 7;
	const t = interpolate(frame, [hit - fall, hit], [0, 1], {...clamp, easing: slamIn});
	const settle = spring({frame: frame - hit, fps, config: {damping: 11, stiffness: 260, mass: 0.5}});
	const pre = frame < hit ? interpolate(t, [0, 1], [1.9, 1]) : 1 - 0.04 * (1 - settle) * Math.sin(settle * Math.PI);
	const opacity = interpolate(frame, [hit - fall, hit - fall + 3], [0, 1], clamp);
	const blur = frame < hit ? (1 - t) * 14 : 0;
	const cx = (x0 + x1) / 2;
	const cy = (y0 + y1) / 2;
	return (
		<Full
			src={layer('kicks')}
			style={{
				clipPath: `inset(${y0}px ${1920 - x1}px ${1080 - y1}px ${x0}px)`,
				transformOrigin: `${cx}px ${cy}px`,
				transform: `scale(${pre})`,
				filter: `blur(${blur}px)`,
				opacity,
			}}
		/>
	);
};

// Animated film grain.
const Grain: React.FC<{frame: number}> = ({frame}) => (
	<svg width={1920} height={1080} style={{position: 'absolute', inset: 0, mixBlendMode: 'overlay', opacity: 0.22}}>
		<filter id="grain" x="0" y="0" width="100%" height="100%">
			<feTurbulence type="fractalNoise" baseFrequency="0.85" numOctaves={2} seed={frame % 97} stitchTiles="stitch" />
			<feColorMatrix type="saturate" values="0" />
		</filter>
		<rect width="100%" height="100%" filter="url(#grain)" />
	</svg>
);

export const RealityKicksIn: React.FC = () => {
	const frame = useCurrentFrame();
	const {fps, durationInFrames} = useVideoConfig();
	const cam = useCamera(frame, durationInFrames);

	// Opening: exposure up from black while the lens racks into focus.
	const exposure = interpolate(frame, [0, 22], [0, 1], {...clamp, easing: Easing.out(Easing.quad)});
	const focus = interpolate(frame, [0, 34], [9, 0], {...clamp, easing: expoOut});
	const fadeOut = interpolate(frame, [durationInFrames - 16, durationInFrames - 1], [1, 0], {
		...clamp,
		easing: Easing.in(Easing.quad),
	});
	// Each hit knocks the exposure down for a couple of frames.
	const hitDip = 1 - 0.1 * Math.exp(-Math.max(0, frame - KICKS_HIT) / 2.5) * (frame >= KICKS_HIT ? 1 : 0)
		- 0.06 * Math.exp(-Math.max(0, frame - IN_HIT) / 2.5) * (frame >= IN_HIT ? 1 : 0);

	// Practical lights inside the flats.
	const tvStep = Math.floor(frame / 3);
	const tv = 0.26 + 0.18 * (random(`tv-${tvStep}`) - 0.5) + 0.06 * noise('tvs', frame / 10);
	const laptop = 0.2 + 0.04 * noise('lap', frame / 14);
	const breathe = (s: string) => 0.2 + 0.05 * noise(s, frame / 20);
	// the top-floor lamp stutters once, late in the shot
	const stutter = frame >= 150 && frame < 160 ? (random(`st-${frame}`) > 0.45 ? 0.35 : 1) : 1;

	return (
		<AbsoluteFill style={{backgroundColor: '#000'}}>
			<AbsoluteFill style={{opacity: exposure * fadeOut * hitDip}}>
				<Depth cam={cam} depth={1} style={{filter: focus > 0.05 ? `blur(${focus}px)` : undefined}}>
					<Full src={layer('plate')} />
					<Glow name="glow_tv" opacity={tv} />
					<Glow name="glow_laptop" opacity={laptop} />
					<Glow name="glow_pendant" opacity={breathe('pd')} />
					<Glow name="glow_lamp_top" opacity={breathe('lt') * stutter} />
					<Glow name="glow_lamp_mid" opacity={breathe('lm')} />
					<Glow name="glow_lamp_low" opacity={breathe('ll')} />
					<MinuteHand frame={frame} fps={fps} />
					<Full src={layer('hub')} />
				</Depth>

				{/* type sits slightly in front of the illustration */}
				<Depth cam={cam} depth={1.3}>
					<RealityLine frame={frame} />
					<SlamWord frame={frame} fps={fps} hit={KICKS_HIT} box={[118, 440, 486, 580]} />
					<SlamWord frame={frame} fps={fps} hit={IN_HIT} box={[492, 440, 676, 580]} />
				</Depth>

				{/* soft key light from top-left, breathing very slowly */}
				<AbsoluteFill
					style={{
						background:
							'radial-gradient(ellipse 70% 60% at 18% 8%, rgba(255,236,220,1) 0%, rgba(255,236,220,0) 70%)',
						mixBlendMode: 'soft-light',
						opacity: 0.28 + 0.06 * noise('key', frame / 30),
					}}
				/>
				{/* vignette */}
				<AbsoluteFill
					style={{
						background:
							'radial-gradient(ellipse 75% 70% at 52% 48%, rgba(0,0,0,0) 55%, rgba(0,0,0,0.55) 100%)',
					}}
				/>
			</AbsoluteFill>
			<Grain frame={frame} />
		</AbsoluteFill>
	);
};
